### ISSUE TITLE
alarm模块一直报错“rpc.go:28: listener accept error: accept tcp [::]:1986: accept4: too many open files”

### ISSUE THREAD

**Issue by showmeall** [710leo/urlooker#11]
alarm模块一直报错“rpc.go:28: listener accept error: accept tcp [::]:1986: accept4: too many open files”，导致日志文件暴涨

**Comment by 710leo** [comment]
@showmeall 能贴下具体的日志吗？可以加下 urlooker交流群反馈详细情况  群号: 556988374

**Comment by fxltsbl3855** [comment]
我下载的最新版本v0.0.2 ， 也有这个问题，alarm模块后代抛出同样错误，查看os连接，1986端口连接数2k多，http://{$IP}:1984  这个地址无响应；
个人猜测应该是连接创建太多

**Comment by 710leo** [comment]
@showmeall @fxltsbl3855 多谢反馈，问题已修复，可以到这看[详情](https://github.com/URLooker/web/commit/ae289461c71bf466bfcd22f70211e5bb708bac85)
