### ISSUE TITLE
建议增加 指定IP访问域名的功能

### ISSUE THREAD

**Issue by starjoe** [710leo/urlooker#14]
所谓的指定IP访问域名的类似实现方式我知道的只有
1、host文件
2、通过 curl -H ‘Host:baidu.com ’ http://10.12.20.21 

使用场景就是 在CDN下，检查域名回源的情况。

建议就是 这个IP 是个检测可选项，如果不填写的话那就是从过agent获取的IP 来做测试，如果填写的话就是通过填写的IP 来做测试！

**Comment by liuts** [comment]
我们这里也需要这个的功能。

**Comment by 710leo** [comment]
@starjoe @liuts 这个功能已经加上: )

**Comment by liuts** [comment]
太棒了，我也要学习golang，完善项目
