### ISSUE TITLE
创建团队报错 strconv.ParseInt: parsing "xxxx": invalid syntax

### ISSUE THREAD

**Issue by coolwind8214** [710leo/urlooker#22]
![image](https://user-images.githubusercontent.com/32867316/54737252-fddb9480-4be9-11e9-9779-b3c61b6ebc5c.png)

**Comment by 710leo** [comment]
@coolwind8214 最新版本问题没有复现 close

**Comment by leoiceo** [comment]
最新版本出了同样的问题！

**Comment by leoiceo** [comment]
recovery.go:37: [team_handler.go:97] 2019-07-23 19:49:28 [Error:]strconv.ParseInt: parsing "admin": invalid syntax
