### ISSUE TITLE
新建组报错

### ISSUE THREAD

**Issue by pkarqi** [710leo/urlooker#25]
![image](https://user-images.githubusercontent.com/8895661/65667204-cefb1b00-e071-11e9-9bd7-68878a2a72c2.png)

**Comment by pkarqi** [comment]
新建组报错

**Comment by opslx** [comment]
一样啊，百度也搜不到，要疯了

**Comment by 710leo** [comment]
@pkarqi @1655996094 前端的兼容问题，换个浏览器即可
