### ISSUE TITLE
check.go:36: no found item assigned to

### ISSUE THREAD

**Issue by jwping** [710leo/urlooker#26]
[root@localhost urlooker]# cat logs/agent/stdout.log
configContent:
debug: false
hostname: "hostname1"
worker: 1000
web:
  addrs: ["127.0.0.1:1985"]
  interval: 60
  timeout: 10002019/11/28 03:43:10 config.go:64: &{false hostname1 1000 0xc0000d4990}
2019/11/28 03:43:10 config.go:65: load configuration file configs/agent.yml successfully
g.Config.Web.Addrs:  &{false hostname1 1000 0xc0000d4990}
2019/11/28 03:43:10 check.go:36: no found item assigned to hostname1

这里我已经将agent.yml的hostname与web.yml的monitorMap设置一致，如下：
agent.yml：
hostname: "hostname1"

web.yml：
monitorMap:
    default: ["hostname1"]
    idc1: ["hostname.2"]

[root@localhost urlooker]# cat logs/web/stdout.log
2019/11/28 03:43:10 config.go:113: &{false [admin] e84d0755dda7a538315ea7a95a8c36af true 30 12  0xc0000991c0 0xc000120780 0xc00015d420 <nil> 0xc0000991e0 0xc0000aa550 0xc000099320 0xc000099340 map[default:[hostname1] idc1:[hostname.2]]}
2019/11/28 03:43:10 config.go:115: load configuration file configs/web.yml successfully
2019/11/28 03:43:10 mysql.go:18: &{false [admin] e84d0755dda7a538315ea7a95a8c36af true 30 12  0xc0000991c0 0xc000120780 0xc00015d420 <nil> 0xc0000991e0 0xc0000aa550 0xc000099320 0xc000099340 map[default:[hostname1] idc1:[hostname.2]]}
[negroni] listening on 0.0.0.0:1984
2019/11/28 03:43:10 rpc.go:24: listening on 0.0.0.0:1985

**Comment by jwping** [comment]
发现web log存在报错：
[root@localhost urlooker]# cat logs/web/stdout.log
2019/11/28 03:43:10 config.go:113: &{false [admin] e84d0755dda7a538315ea7a95a8c36af true 30 12  0xc0000991c0 0xc000120780 0xc00015d420 <nil> 0xc0000991e0 0xc0000aa550 0xc000099320 0xc000099340 map[default:[hostname1] idc1:[hostname.2]]}
2019/11/28 03:43:10 config.go:115: load configuration file configs/web.yml successfully
2019/11/28 03:43:10 mysql.go:18: &{false [admin] e84d0755dda7a538315ea7a95a8c36af true 30 12  0xc0000991c0 0xc000120780 0xc00015d420 <nil> 0xc0000991e0 0xc0000aa550 0xc000099320 0xc000099340 map[default:[hostname1] idc1:[hostname.2]]}
[negroni] listening on 0.0.0.0:1984
2019/11/28 03:43:10 rpc.go:24: listening on 0.0.0.0:1985
2019/11/28 03:43:10 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'
2019/11/28 03:43:11 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'
2019/11/28 03:43:12 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'
2019/11/28 03:43:13 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'
2019/11/28 03:43:14 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'
2019/11/28 03:43:15 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'
2019/11/28 03:43:16 fetcher.go:30: get strategies error: Error 1054: Unknown column 'method' in 'field list'

**Comment by 710leo** [comment]
@Anshan-pl 你使用的应该是旧代码，最新的代码没有问题
