### ISSUE TITLE
web组件已打开了推送到falcon,产生的报警未恢复却没有在falcon中出现

### ISSUE THREAD

**Issue by oslet** [710leo/urlooker#3]
如题所述，这边配置了一个不能访问的 url地址，已产生了邮件报警并收到邮件，但open-falcon平台中 未恢复的报警页中并未有此内容，请问这个推送内容在 open-falcon中哪里显示,如下是相关截图

![_020](https://cloud.githubusercontent.com/assets/1573303/17723664/6acab848-646e-11e6-89fe-523ca5f2cc26.png)

**Comment by 710leo** [comment]
@oslet 这个告警历史是alarm组件产生的，和open-falcon是没有关系的，有这个信息，说明你在web组件配置文件中开启了alarm。
推送给open-falcon的数据可以在falcon的dashboard组件查看，推送的数据格式见[wiki](http://www.dwz.cn/3Y9M5d)
