### ISSUE TITLE
agent的log里有个报错，即使设置相同了还在报错

### ISSUE THREAD

**Issue by littleheary** [710leo/urlooker#31]
configContent:
debug: false
hostname: "localhost"
worker: 1000
web:
  addrs: ["127.0.0.1:1985"]
  interval: 60
  timeout: 10002020/02/14 16:38:04 config.go:64: &{false localhost 1000 0xc0000fa630}
2020/02/14 16:38:04 config.go:65: load configuration file configs/agent.yml successfully
g.Config.Web.Addrs:  &{false localhost 1000 0xc0000fa630}
2020/02/14 16:38:04 check.go:36: no found item assigned to localhost

这里，我在web.yml中也设置的是localhost，但是依然报错。

而且，图表也一直都是空的。

**Comment by 710leo** [comment]
@littleheary 这个没有复现，已调整策略分发方式，可以用最新版本试试
