### ISSUE TITLE
strconv.ParseInt: parsing "admin": invalid syntax

### ISSUE THREAD

**Issue by hifour** [710leo/urlooker#33]
recovery.go:37: [team.go:97] 2020-03-07 23:44:27 [Error:]strconv.ParseInt: parsing "admin": invalid syntax

在第一次使用admin账号进入urlooker之后，在没有监控任何API的情况下，设置告警用户组，显示如上报错。并且在sign up其他账号之后，创建用户组时，依然显示以上错误。

**Comment by 710leo** [comment]
@hifour 看这里 [FAQ](https://github.com/710leo/urlooker/wiki/FAQ#qstrconvparseint-parsing-user-invalid-syntax-%E5%88%9B%E5%BB%BA%E5%9B%A2%E9%98%9F%E6%8A%A5%E8%BF%99%E4%B8%AA%E9%94%99)
