### ISSUE TITLE
Alarm history 显示错误，不显示或显示的数量少

### ISSUE THREAD

**Issue by Yasil** [710leo/urlooker#38]
Alarm history 显示错误，不显示或显示的数量少

**Comment by 710leo** [comment]
@Yasil 提供一下更详细的信息吧，截图，日志

**Comment by Yasil** [comment]
好的. 
centos7 
数据库是 mariadb
tem_status00表的部分数据
1494	1	x.x.x.x	162	200	1585960150	2
1495	1	x.x.x.x	163	200	1585960170	2
1496	1	x.x.x.x	132	200	1585960190	2
1497	1	x.x.x.x	80	200	1585960210	2
1498	2	x.x.x.x	181	200	1585960210	3
1499	1	x.x.x.x	198	200	1585960230	2
1500	1	x.x.x.x	82	200	1585960250	2
1501	2	x.x.x.x	195	200	1585960250	3
1502	1	x.x.x.x	84	200	1585960270	2
1503	2	x.x.x.x	165	200	1585960270	3
1504	1	x.x.x.x	183	200	1585960290	2
1505	1	x.x.x.x	194	200	1585960310	2

event 表是空的

strategy表的设置数据
INSERT INTO `urlooker`.`strategy` (`id`, `url`, `idc`, `enable`, `keywords`, `endpoint`, `timeout`, `creator`, `data`, `ip`, `expect_code`, `tag`, `header`, `method`, `post_data`, `note`, `max_step`, `times`, `teams`) VALUES ('1', 'https://www.dogedoge.com', 'default', '1', '58584455858585858444541212.12.', '', '1000', 'admin', '', '', '3', '', '', 'get', '', '验证状态码', '1', '3', '1');
INSERT INTO `urlooker`.`strategy` (`id`, `url`, `idc`, `enable`, `keywords`, `endpoint`, `timeout`, `creator`, `data`, `ip`, `expect_code`, `tag`, `header`, `method`, `post_data`, `note`, `max_step`, `times`, `teams`) VALUES ('2', 'https://www.hao123.com', 'default', '1', '898556564121312asdfaweww', '', '1000', 'admin', '', '', '200', '', '', 'get', '', '超时警告', '1', '1', '2');


alarm.yml
rpc:
    listen: "0.0.0.0:1986"
web: 
    addrs: 
      - "127.0.0.1:1985"
    timeout: 300 
    interval: 30 #get strategy interval
smtp: 
    addr: "smtp.qq.com"
    username: "xxxx@qq.com"
    password: "fgnxxxxxxxhha"
    from: "xxxx@qq.com"
worker: 
    sms: 10  #send sms concurrency
    mail: 50 #send mail concurrency
# remain: 30

web.yml
alarm: #告警判断组件，为true表示使用alarm组件
    enable: true 
    batch: 200
    replicas: 500
    connTimeout: 1000
    callTimeout: 5000
    maxConns: 32
    maxIdle: 32
    sleepTime: 5
    cluster:
    node-1: "127.0.0.1:1986"

agent log
2020/04/04 08:36:50 utils.go:50: [detect]:sid:1 domain:www.dogedoge.com result:2
2020/04/04 08:36:50 utils.go:50: [detect]:sid:2 domain:www.hao123.com result:3
2020/04/04 08:37:10 check.go:33: default
2020/04/04 08:37:10 utils.go:50: [detect]:sid:1 domain:www.dogedoge.com result:2
2020/04/04 08:37:10 utils.go:50: [detect]:sid:2 domain:www.hao123.com result:3
2020/04/04 08:37:30 check.go:33: default
2020/04/04 08:37:30 utils.go:50: [detect]:sid:1 domain:www.dogedoge.com result:2
2020/04/04 08:37:30 utils.go:50: [detect]:sid:2 domain:www.hao123.com result:3
2020/04/04 08:37:50 check.go:33: default
2020/04/04 08:37:50 utils.go:50: [detect]:sid:1 domain:www.dogedoge.com result:2
2020/04/04 08:37:50 utils.go:50: [detect]:sid:2 domain:www.hao123.com result:3
2020/04/04 08:38:10 check.go:33: default
2020/04/04 08:38:10 utils.go:50: [detect]:sid:1 domain:www.dogedoge.com result:2
2020/04/04 08:38:10 utils.go:50: [detect]:sid:2 domain:www.hao123.com result:3

alarm log
2020/04/04 08:24:50 config.go:83: load configuration file configs/alarm.yml successfully
2020/04/04 08:24:50 rpc.go:22: listen on.. 0.0.0.0:1986

web log
目前看历史图表的时候
2020/04/04 08:37:50 item.go:49: error: empty circle
2020/04/04 08:38:10 item.go:49: error: empty circle
2020/04/04 08:38:11 item.go:49: error: empty circle
2020/04/04 08:38:30 item.go:49: error: empty circle
2020/04/04 08:38:50 item.go:49: error: empty circle
2020/04/04 08:39:10 item.go:49: error: empty circle
2020/04/04 08:39:11 item.go:49: error: empty circle

**Comment by Yasil** [comment]
mysql maria 差距不那么大.  就算是兼容... 也不会有太大大出入
何况MYSQL的版本我也试过了的. Alarm history 和告警也同样有一些BUG

**Comment by 710leo** [comment]
@Yasil event表是空的，alarm也没有报错，说明并没有产生告警事件，或者你的web和alarm配置有问题，把web的配置文件也贴一下吧
