### ISSUE TITLE
n9e能看到监控数据但不能触发告警

### ISSUE THREAD

**Issue by nondevops** [710leo/urlooker#44]
@urlooker添加域名并正确传到了n9e，设置了触发告警的条件，按照实际情况应该要触发告警，但是当前未触发告警，告警邮件通道是正常工作的。可以帮忙瞧一瞧这个问题吗？@710leo

![`BRMR$XL1X67LTJ%U% {%5T](https://user-images.githubusercontent.com/12181410/91056813-06df5980-e659-11ea-90fe-caaf300e8d55.png)
![WWJC}Y`QD@I``}OX5F0 865](https://user-images.githubusercontent.com/12181410/91056824-0941b380-e659-11ea-862a-b2bd70c91f8e.png)

我的需求描述：
不通过urlooker-alarm组件发出告警（需要在urlooker维护组织关系，n9e已经有了。且不支持多告警通道），希望在n9e控制端看到urlooker的监控数据，同时能从n9e发出告警消息。

已处置措施，未能解决：
1.停止urlooker-alarm服务；
[root@aliyun urlooker]# systemctl status urlooker-alarm
● urlooker-alarm.service - urlooker-alarm for Nightingale
   Loaded: loaded (/usr/lib/systemd/system/urlooker-alarm.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

2.在configs/web.yml配置文件中关闭alarm组件配置，设置为false
具体信息如下：
alarm: #告警判断组件，为true表示使用alarm组件
    enable: false
    batch: 200
    replicas: 500
    connTimeout: 1000
    callTimeout: 5000
    maxConns: 32
    maxIdle: 32
    sleepTime: 30
    cluster:
        node-1: "127.0.0.1:1986"

falcon: #为 true 表示要向 falcon 或者 nightingale 推送数据
    enable: true
    #addr: "http://transfer.addr/api/push"
    addr: "http://127.0.0.1:2058/api/collector/push"
    interval: 60

statsd:
    enable: false
    addr: "ip:port"

prom:
    enable: false
    addr: "ip:port"

**Comment by 710leo** [comment]
监控策略的阈值配置错了，改成>=3000，就有会报警
