### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by lupus721** [710leo/urlooker#5]
简单反馈一下
各种说明写的实在是太简略了，对高手可能没问题，对新入门的菜鸟，好头大啊
现在已经跑起来了，有这么几个问题
1 用户这部分好歹加个限制或者配置文件里来个开关，不然谁都能注册，实在是个头疼的事情，用户管理如何做
2 现在添加了几个网站有一个网站图表上有ip地址和响应时间的曲线，但是下面部分完全没有显示，状态，url，ip地址，全部为空的，这是什么个情况啊
3 首页能不能有个dashboard之类的，好歹显示当前x个网站正常，x个不正常
4 https是否支持了

**Comment by 710leo** [comment]
@lupus721 多谢反馈建议
1和3后面有时间了完善一下
第2条 下面的表格展示的是告警历史，这块儿已经做了优化，只有触发告警了才会看到表格
第4条 由于是内网应用，暂时不考虑支持https
