### ISSUE TITLE
有一些疑问需要请教

### ISSUE THREAD

**Issue by jinlongwang** [710leo/urlooker#7]
1.关于域名解析
看代码中现在是在web端把解析好的IP下发到agnet上，agent对ip进行GET操作来判断是否ok。感觉这块是不是应该放到agent上来做？ 因为对于做了cdn的域名来说， 我的agent可能是部署在各个地区的， 这样解析出来的ip应该是不一样的。

2.关于web端缓存策略
web配置文件中是可以配置多了机房的， 比如

```
 "monitorMap": {
        "default":["A", "B"],
},
```

看到代码中有一段是

```
func Getkey(idc string) string {
    keys := g.Config.MonitorMap[idc]
    count := len(keys)
    now := int(time.Now().Unix())
    return keys[now%count]
}

```

这样的效果是有一批策略是A机器来处理，另一批策略是B来处理.
想知道这样的设计是基于什么样的考虑呢？

谢谢

**Comment by 710leo** [comment]
问题1：对于你说的同一个域名不同地区ip不同的问题，这个其实有一个自定义函数接口，你们公司应该有一个配置域名解析的系统，这个系统提供一个域名-机房-IP的对应关系，web组件通过自定义函数获取到对应关系，这样每个机房agent根据idc字段都能拿到对应的ip。在agent端解析会有两个问题：a.跨机房监控时，获取到ip不全；b.无法水平扩展

问题2：这个是为了当待检测的目标过多，单台机器上的agent一个周期处理不完时，可以将待检测目标分散到多台机器。

**Comment by jinlongwang** [comment]
了解了 多谢回复
