### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by angelinazf** [710leo/urlooker#8]
您好，初学者想看看你的代码学习学习，但是提供的[http://x2know.qiniudn.com/urlooker.tar.gz](url)地址已经无法下载，并且直接clone源码包里面有很多依赖已经不能使用，导致项目无法运行起来，麻烦你能重新提供一份完整的源码吗？

**Comment by 710leo** [comment]
@agelinazf 上面的下载地址已经可以用了
另，源码安装也没有问题，按照每个组件安装文档的步骤操作即可

**Comment by angelinazf** [comment]
好的，谢谢。
